/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
// biome-ignore lint: disable
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    AxisChart: typeof import('./src/components/AxisChart/index.vue')['default']
    DataTableV2: typeof import('./src/components/DataTableV2/index.vue')['default']
    ElButton: typeof import('element-plus/es')['ElButton']
    EvaluationTable: typeof import('./src/components/EvaluationTable/index.vue')['default']
    Loading: typeof import('./src/components/Loading/index.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SvgIcon: typeof import('./src/components/SvgIcon/index.vue')['default']
    UpdateVersion: typeof import('./src/components/UpdateVersion/index.vue')['default']
  }
}
